✨ app: add withdrawal processing view
exactly/mobile pull request #228
Opened 2024-12-16 17:50 UTC by franm91

closes #165

2024-12-16 18:50 UTC, dieguezguille approved these changes

2024-12-17 09:02 UTC, cruzdanilo requested changes

2024-12-17 09:02 UTC, cruzdanilo commented on src/components/home/Processing.tsx
> +type Proposal = [amount: bigint, market: `0x${string}`, recipient: `0x${string}`, timestamp: bigint];
don't redeclare types from abi. they are auto-generated.

2024-12-17 09:02 UTC, cruzdanilo commented on src/components/home/Processing.tsx
> +  }) as { data: Proposal | undefined };
wagmi hooks are strictly typed, there's no need to use type assertion here (`as`)

2024-12-17 09:02 UTC, cruzdanilo commented on src/components/home/Processing.tsx
> +      },
what happens when there's no proposal?

2024-12-17 14:55 UTC, franm91 commented on src/components/home/Processing.tsx
> +type Proposal = [amount: bigint, market: `0x${string}`, recipient: `0x${string}`, timestamp: bigint];
fixed

2024-12-17 14:55 UTC, franm91 commented on src/components/home/Processing.tsx
> +  }) as { data: Proposal | undefined };
fixed

2024-12-17 14:56 UTC, franm91 commented on src/components/home/Processing.tsx
> +      },
fixed

2024-12-17 18:56 UTC, dieguezguille approved these changes
LGTM now 🆗

2024-12-18 17:35 UTC, dieguezguille submitted a review, later dismissed

2024-12-26 14:29 UTC, cruzdanilo approved these changes

2024-12-26 14:35 UTC, merged